env:
  es6: true
  node: true
  mocha: true

extends:
  - airbnb

plugins:
  - import

rules:
  #Allow _id on mongo id attributes and rewire __get__
  no-underscore-dangle: [error, {allow: [_id, __get__]}]

  #Allow devDependencies for tests
  import/no-extraneous-dependencies: [error, {devDependencies: ['**/*.test.js']}]

  #Allow comment decoration with ****
  spaced-comment: [error, always, {exceptions: ['*']}]

  #Allow uppercase functions with mongoose
  new-cap: [error, {capIsNewExceptions: ['mongoose.Schema', 'mongoose.Types.ObjectId']}]

  #Ignore unused-var error message on chai.should()
  no-unused-vars: [error, {varsIgnorePattern: 'should'}]

  #Allow for of loops as forEach does not work with async await (yet)
  no-restricted-syntax: [warn, ForOfStatement, ForInStatement]

  #Allow extending Array with chunk method for readability
  no-extend-native: [warn]

  #Allow param-reassign on annoSetLabelMap in importFullTexts:
  no-param-reassign: [error, {props: true, ignorePropertyModificationsFor: [annoSetLabelMap]}]

  #Allow (pep) Python-style parameters indentation and alignment
  indent: [error, 2, {FunctionDeclaration: {parameters: first}, FunctionExpression: {parameters: first}, CallExpression: {arguments: first}, ArrayExpression: first, ObjectExpression: first}]

  #Allow await-in-loop while we look for a better solution
  no-await-in-loop: [warn]

  #Allow calls to object properties instead of using destructuring
  prefer-destructuring: [error, {VariableDeclarator: {object: false}}]

  #Avoid function-paren-newline to simulate python-style function params style
  function-paren-newline: [error, never]
